title: Default
fields:
  content_fields: content_fields
  sections:
    label: Sections
    type: structure
    modalsize: large
    fields:
      text:
        label: Text
        type: markdown
        required: true
      image:
        label: Image
        type: image
        required: true