title: Products
pages: false
files:
  sortable: true
fields:
  tabProducts:
    label: Products
    type:  tabs
    icon: file-text-o
  products:
    label: Products
    type: structure
    modalsize: large
    entry: >
      <img src="/content/2-products/{{featured_image}}"><br>
      <strong>{{name}}</strong><br>
      {{category}}<br>
      ${{price}}
    fields:
      id:
        type: hidden
      name:
        label: Title
        type: text
        required: true
      text:
        label: Product Description
        type: markdown
        required: true
      price:
        label: Price
        type: number
        step: .01
        required: true
        placeholder: e.g. 1.25
        width: 1/2
      category:
        label: Category
        type: select
        width: 1/2
        required: true
        options: field
        field:
          name: categories
      product_id:
        label: Product ID
        type: text
        required: true
        width: 1/2
      quantity:
        label: Stock
        type: number
        required: true
        width: 1/2
      featured_image:
        label: Featured Image
        type: image
        required: true
      images:
        label: Other Images
        type: images
  content_fields: content_fields
  category_description:
    label: Category Description
    type: markdown
    required: true
  menu_image:
    label: Menu Image
    type: image
    required: true
  categories:
    label: Product Categories
    type: tags
  category_descriptions:
    label: Descriptions and Featured Image Per Category
    type: structure
    modalsize: large
    entry: >
      <img src="/content/2-products/{{featured_image}}"><br>
      <strong>{{category}}</strong><br>
      {{text}}
    fields:
      category:
        label: Category
        type: select
        required: true
        options: field
        field:
          name: categories
      text:
        label: Text
        type: markdown
      featured_image:
        label: Featured Image
        type: image
        required: true