title: Product List
pages: product-category
fields:
  tabContent:
    label: Content
    type:  tabs
    icon: file-text-o
  title:
    label: Title
    type:  text
  menu_title:
    label: Menu Title
    type:  text
  background: background
  text:
    label: Text
    type: markdown
    required: true
  category_description:
    label: Category Description
    type: markdown
    required: true