title: Product
fields:
  tabContent:
    label: Content
    type:  tabs
    icon: file-text-o
  title:
    label: Title
    type:  text
  text:
    label: Text
    type: markdown
    required: true
  short_description:
    label: Short Description
    type: text
    required: true
  primary_image:
    label: Primary Image
    type: image
    required: true
  tabDetails:
    label: Details
    type:  tabs
    icon: file-text-o
  product_id:
    label: Product ID
    readonly: true
    width: 1/2
  quantity:
    label: Quantity
    type: number
    width: 1/2
    required: true
  price:
    label: Price
    type: number
    step: .01
    placeholder: e.g. 1.25
    required: true