title: Site
fields:
  tabSettings:
    label: Settings
    type:  tabs
    icon: gear
  title:
    label: Title
    type:  text
  background:
    label: Default Background
    type: image
    width:  1/2
    required: true
  notify_limit:
    label: Low Stock Count
    type: number
    width:  1/2
    required: true
  birthstone_price:
    label: Birthstone Price
    type: number
    step: .01
    required: true
    placeholder: e.g. 1.25
    width: 1/2
  engraving_price:
    label: Engraving Price
    type: number
    step: .01
    required: true
    placeholder: e.g. 1.25
    width: 1/2
  # shipping_methods:
  #   label: Shipping Methods
  #   type: structure
  #   modalsize: large
  #   style: table
  #   fields:
  #     shipping_id:
  #       label: ID
  #       type: text
  #       required: true
  #     text:
  #       label: Text
  #       type: Text
  #       required: true
  #     price:
  #       label: Price
  #       type: number
  #       step: .01
  #       required: true

  tabForm:
    label: Form
    type:  tabs
    icon: file-text-o
  form_title:
    label: Form Title
    type: text
    required: true
  map_text:
    label: Map Text
    type: text
    required: true
  address:
    label: Address
    type: markdown
    required: true
  phone:
    label: Phone Number
    type: Text
    required: true
  office_hours:
    label: Office Hours
    type: markdown
    required: true

  tabFooter:
    label: Footer
    type:  tabs
    icon: file-text-o
  copyright:
    label: Copyright
    type:  markdown
    required: true
  social_title:
    label: Social Media Title
    type: Text
    required: true
  social_media:
    label: Social Media Links
    type: structure
    modalsize: large
    style: table
    required: true
    fields:
      social_title:
        label: Title
        type: text
        required: true
      social_link:
        label: Link
        type: url
        required: true

  tabComingSoon:
    label: Coming Soon
    type:  tabs
    icon: file-text-o
  coming_text:
    label: Text
    type: markdown
    required: true
  bottom_image:
    label: Bottom Image
    type: image
    required: true